# Generated by Django 3.1.14 on 2022-09-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-club_count'], 'verbose_name': '카테고리', 'verbose_name_plural': '카테고리'},
        ),
    ]
