# Generated by Django 3.1.14 on 2022-09-26 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0002_club_user'),
        ('pins', '0002_postpin_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_pins', to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
        migrations.AddField(
            model_name='clubpin',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_pins', to='clubs.club', verbose_name='클럽'),
        ),
        migrations.AddField(
            model_name='clubpin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_pins', to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
        migrations.AlterUniqueTogether(
            name='postpin',
            unique_together={('post', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='clubpin',
            unique_together={('club', 'user')},
        ),
    ]
