# Generated by Django 3.1.14 on 2022-09-26 22:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import superclub.apps.comments.models.mixins.image
import superclub.bases.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('like_count', models.IntegerField(default=0, verbose_name='좋아요 수')),
                ('dislike_count', models.IntegerField(default=0, verbose_name='싫어요 수')),
                ('image', models.ImageField(blank=True, null=True, upload_to=superclub.apps.comments.models.mixins.image.image_path, verbose_name='이미지')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='이미지 URL')),
                ('profile_data', models.JSONField(blank=True, null=True, verbose_name='프로필 데이터')),
                ('content', models.CharField(max_length=2000, verbose_name='내용')),
                ('is_secret', models.BooleanField(default=False, verbose_name='비밀 댓글 여부')),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='clubs.club', verbose_name='클럽')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
                'db_table': 'comments',
                'ordering': ['-created'],
            },
            bases=(superclub.bases.models.UpdateMixin, models.Model),
        ),
    ]
