# Generated by Django 3.1.14 on 2022-09-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_comment_report_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='report_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='최근 신고 날짜'),
        ),
    ]
