# Generated by Django 3.1.14 on 2022-09-29 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_comment_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='child_comment_data',
            field=models.JSONField(blank=True, null=True, verbose_name='자식 댓글 데이터'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comments.comment', verbose_name='부모 댓글'),
        ),
    ]
