# Generated by Django 3.1.14 on 2022-09-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-post_count'], 'verbose_name': '태그', 'verbose_name_plural': '태그'},
        ),
    ]
