# Generated by Django 3.1.14 on 2022-09-26 22:55

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import superclub.bases.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubDailyCommentCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('count', models.IntegerField(default=0, verbose_name='일별 댓글 수')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='댓글 날짜')),
            ],
            options={
                'verbose_name': '일별 댓글',
                'verbose_name_plural': '일별 댓글',
            },
            bases=(superclub.bases.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ClubDailyMemberCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('count', models.IntegerField(default=0, verbose_name='일별 가입 수')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='가입 날짜')),
            ],
            options={
                'verbose_name': '일별 가입',
                'verbose_name_plural': '일별 가입',
            },
            bases=(superclub.bases.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ClubDailyPostCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('count', models.IntegerField(default=0, verbose_name='일별 포스트 수')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='포스트 날짜')),
            ],
            options={
                'verbose_name': '일별 포스트',
                'verbose_name_plural': '일별 포스트',
            },
            bases=(superclub.bases.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ClubDailyViewCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('count', models.IntegerField(default=0, verbose_name='일별 조회수')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='조회 날짜')),
            ],
            options={
                'verbose_name': '일별 조회',
                'verbose_name_plural': '일별 조회',
            },
            bases=(superclub.bases.models.UpdateMixin, models.Model),
        ),
    ]
