# Generated by Django 3.1.14 on 2022-09-26 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club_counts', '0001_initial'),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubdailyviewcount',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_daily_view_counts', to='clubs.club', verbose_name='클럽'),
        ),
        migrations.AddField(
            model_name='clubdailypostcount',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_daily_post_counts', to='clubs.club', verbose_name='클럽'),
        ),
        migrations.AddField(
            model_name='clubdailymembercount',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_daily_member_counts', to='clubs.club', verbose_name='클럽'),
        ),
        migrations.AddField(
            model_name='clubdailycommentcount',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_daily_comment_counts', to='clubs.club', verbose_name='클럽'),
        ),
        migrations.AlterUniqueTogether(
            name='clubdailyviewcount',
            unique_together={('club', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='clubdailypostcount',
            unique_together={('club', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='clubdailymembercount',
            unique_together={('club', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='clubdailycommentcount',
            unique_together={('club', 'date')},
        ),
    ]
