# Generated by Django 3.1.14 on 2022-09-26 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_post_profile'),
        ('comments', '0004_comment_user'),
        ('likes', '0003_postlike_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_likes', to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
        migrations.AddField(
            model_name='postdislike',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_dislikes', to='posts.post', verbose_name='포스트'),
        ),
        migrations.AddField(
            model_name='postdislike',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_dislikes', to='profiles.profile', verbose_name='프로필'),
        ),
        migrations.AddField(
            model_name='postdislike',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_dislikes', to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_likes', to='comments.comment', verbose_name='댓글'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_likes', to='profiles.profile', verbose_name='프로필'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
        migrations.AddField(
            model_name='commentdislike',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_dislikes', to='comments.comment', verbose_name='댓글'),
        ),
        migrations.AddField(
            model_name='commentdislike',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_dislikes', to='profiles.profile', verbose_name='프로필'),
        ),
        migrations.AddField(
            model_name='commentdislike',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_dislikes', to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
    ]
