# Generated by Django 3.1.14 on 2022-09-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0004_auto_20220926_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentdislike',
            name='profile_data',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='profile_data',
        ),
    ]
