# Generated by Django 3.1.14 on 2022-09-26 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0002_club_user'),
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postshare',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_shares', to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
        migrations.AddField(
            model_name='clubshare',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_shares', to='clubs.club', verbose_name='클럽'),
        ),
        migrations.AddField(
            model_name='clubshare',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_shares', to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
    ]
