# Generated by Django 3.1.14 on 2022-09-26 22:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import superclub.apps.clubs.models.mixins.image
import superclub.bases.models
import url_filter.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('comment_count', models.IntegerField(default=0, verbose_name='댓글 수')),
                ('daily_comment_count', models.IntegerField(default=0, verbose_name='일간 댓글 수')),
                ('weekly_comment_count', models.IntegerField(default=0, verbose_name='주간 댓글 수')),
                ('monthly_comment_count', models.IntegerField(default=0, verbose_name='월간 댓글 수')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to=superclub.apps.clubs.models.mixins.image.thumbnail_image_path, verbose_name='썸네일 이미지')),
                ('thumbnail_image_url', models.URLField(blank=True, null=True, verbose_name='썸네일 이미지 URL')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=superclub.apps.clubs.models.mixins.image.profile_image_path, verbose_name='프로필 이미지')),
                ('profile_image_url', models.URLField(blank=True, null=True, verbose_name='프로필 이미지 URL')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to=superclub.apps.clubs.models.mixins.image.banner_image_path, verbose_name='배너 이미지')),
                ('banner_image_url', models.URLField(blank=True, null=True, verbose_name='배너 이미지 URL')),
                ('member_count', models.IntegerField(default=0, verbose_name='멤버 수')),
                ('daily_member_count', models.IntegerField(default=0, verbose_name='일간 멤버 수')),
                ('weekly_member_count', models.IntegerField(default=0, verbose_name='주간 멤버 수')),
                ('monthly_member_count', models.IntegerField(default=0, verbose_name='월간 멤버 수')),
                ('board_permission', models.IntegerField(choices=[(7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=7, verbose_name='게시판 생성/활성/비활성화 권한')),
                ('comment_permission', models.IntegerField(choices=[(7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=7, verbose_name='댓글 활성/비활성화 권한')),
                ('design_permission', models.IntegerField(choices=[(7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=7, verbose_name='클럽 디자인 권한')),
                ('modifying_permission', models.IntegerField(choices=[(7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=9, verbose_name='정보 수정 권한')),
                ('auto_member_registration_permission', models.IntegerField(choices=[(7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=9, verbose_name='자동 가입 권한')),
                ('approval_member_permission', models.IntegerField(choices=[(7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=7, verbose_name='가입 승인 권한')),
                ('restriction_activity_permission', models.IntegerField(choices=[(7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=7, verbose_name='활동 제한 권한')),
                ('restriction_activity_period_permission', models.IntegerField(choices=[(7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=9, verbose_name='활동 제한 기간 설정 권한')),
                ('banishment_permission', models.IntegerField(choices=[(7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=7, verbose_name='퇴출 권한')),
                ('restriction_approval_member_period_permission', models.IntegerField(choices=[(7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=9, verbose_name='가입 제한 기간 설정 꿘한')),
                ('block_permission', models.IntegerField(choices=[(7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=9, verbose_name='차단 권한')),
                ('hand_over_permission', models.IntegerField(choices=[(7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=10, verbose_name='양도 권한')),
                ('transfer_permission', models.IntegerField(choices=[(7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=10, verbose_name='이전 권한')),
                ('independence_permission', models.IntegerField(choices=[(7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=10, verbose_name='독립 권한')),
                ('merge_permission', models.IntegerField(choices=[(7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=10, verbose_name='합병 권한')),
                ('closure_permission', models.IntegerField(choices=[(7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=10, verbose_name='폐쇄 권한')),
                ('modify_permission_by_staff_permission', models.IntegerField(choices=[(7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=9, verbose_name='스탭별 권한 수정 권한')),
                ('post_permission', models.IntegerField(choices=[(7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=7, verbose_name='게시글 활성/비활성화 권한')),
                ('staff_permission', models.IntegerField(choices=[(7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=8, verbose_name='스태프 임명/취소 권한')),
                ('static_permission', models.IntegerField(choices=[(7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=7, verbose_name='통계 관리 권한')),
                ('pin_count', models.IntegerField(default=0, verbose_name='핀 수')),
                ('daily_pin_count', models.IntegerField(default=0, verbose_name='일간 핀 수')),
                ('weekly_pin_count', models.IntegerField(default=0, verbose_name='주간 핀 수')),
                ('monthly_pin_count', models.IntegerField(default=0, verbose_name='월간 핀 수')),
                ('post_count', models.IntegerField(default=0, verbose_name='게시글 수')),
                ('daily_post_count', models.IntegerField(default=0, verbose_name='일간 게시글 수')),
                ('weekly_post_count', models.IntegerField(default=0, verbose_name='주간 게시글 수')),
                ('monthly_post_count', models.IntegerField(default=0, verbose_name='월간 게시글 수')),
                ('share_count', models.IntegerField(default=0, verbose_name='공유 수')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('daily_view_count', models.IntegerField(default=0, verbose_name='일간 조회수')),
                ('weekly_view_count', models.IntegerField(default=0, verbose_name='주간 조회수')),
                ('monthly_view_count', models.IntegerField(default=0, verbose_name='월간 조회수')),
                ('user_data', models.JSONField(blank=True, null=True, verbose_name='관리자 데이터')),
                ('name', models.CharField(error_messages={'unique': 'Already in use. Please enter a different name.'}, max_length=60, unique=True, validators=[url_filter.validators.MinLengthValidator(1)], verbose_name='클럽명')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='설명')),
                ('address', models.CharField(error_messages={'unique': 'Already in use. Please enter a different address.'}, max_length=20, unique=True, validators=[url_filter.validators.MinLengthValidator(1)], verbose_name='주소')),
                ('board_data', models.JSONField(blank=True, null=True, verbose_name='게시판 데이터')),
                ('popularity', models.IntegerField(default=0, verbose_name='인기')),
                ('is_auto_approval', models.BooleanField(default=True, verbose_name='자동 승인 여부')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='categories.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '클럽',
                'verbose_name_plural': '클럽',
                'db_table': 'clubs',
                'ordering': ['-created'],
            },
            bases=(superclub.bases.models.UpdateMixin, models.Model),
        ),
    ]
