# Generated by Django 3.1.14 on 2022-09-30 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='is_public',
        ),
    ]
