# Generated by Django 3.1.14 on 2022-09-26 22:55

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import superclub.bases.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('merge_permission', models.IntegerField(choices=[(7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=7, verbose_name='게시판 합병')),
                ('club_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='클럽 이름')),
                ('board_group_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='그룹 이름')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('description', models.CharField(blank=True, max_length=160, null=True, verbose_name='설명')),
                ('read_permission', models.CharField(choices=[(0, 'GUEST'), (1, 'BRONZE'), (2, 'SILVER'), (3, 'GOLD'), (4, 'PLATINUM'), (5, 'DIAMOND'), (6, 'LEGEND'), (7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=0, max_length=100, verbose_name='읽기 권한')),
                ('write_permission', models.CharField(choices=[(0, 'GUEST'), (1, 'BRONZE'), (2, 'SILVER'), (3, 'GOLD'), (4, 'PLATINUM'), (5, 'DIAMOND'), (6, 'LEGEND'), (7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=1, max_length=100, verbose_name='쓰기 권한')),
                ('view_mode', models.CharField(choices=[('LIST_TYPE', 'LIST_TYPE'), ('ALBUM_TYPE', 'ALBUM_TYPE'), ('CARD_TYPE', 'CARD_TYPE')], default='LIST_TYPE', max_length=100, verbose_name='뷰 모드')),
                ('type', models.CharField(choices=[('NORMAL', 'NORMAL'), ('ALL', 'ALL'), ('NOTICE', 'NOTICE'), ('EVENT', 'EVENT'), ('GALLERY', 'GALLERY'), ('VIDEO', 'VIDEO')], default='NORMAL', max_length=100, verbose_name='타입')),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='순서')),
            ],
            options={
                'verbose_name': '게시판',
                'verbose_name_plural': '게시판',
                'db_table': 'boards',
                'ordering': ['order'],
            },
            bases=(superclub.bases.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BoardGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('club_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='이름')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='순서')),
                ('type', models.CharField(choices=[('NORMAL', 'NORMAL'), ('DEFAULT', 'DEFAULT')], default='NORMAL', max_length=100, verbose_name='타입')),
            ],
            options={
                'verbose_name': '게시판 그룹',
                'verbose_name_plural': '게시판 그룹',
                'db_table': 'board_groups',
                'ordering': ['order'],
            },
            bases=(superclub.bases.models.UpdateMixin, models.Model),
        ),
    ]
