# Generated by Django 3.1.14 on 2022-09-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20220926_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgroup',
            name='merge_permission',
            field=models.IntegerField(choices=[(7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=7, verbose_name='게시판 그룹 합병'),
        ),
        migrations.AlterField(
            model_name='board',
            name='read_permission',
            field=models.IntegerField(choices=[(0, 'GUEST'), (1, 'BRONZE'), (2, 'SILVER'), (3, 'GOLD'), (4, 'PLATINUM'), (5, 'DIAMOND'), (6, 'LEGEND'), (7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=0, verbose_name='게시글 조회 권한'),
        ),
        migrations.AlterField(
            model_name='board',
            name='write_permission',
            field=models.IntegerField(choices=[(0, 'GUEST'), (1, 'BRONZE'), (2, 'SILVER'), (3, 'GOLD'), (4, 'PLATINUM'), (5, 'DIAMOND'), (6, 'LEGEND'), (7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=1, verbose_name='게시글 작성 권한'),
        ),
    ]
