# Generated by Django 3.1.14 on 2022-09-26 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('club_tags', '0001_initial'),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubtag',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_tags', to='clubs.club', verbose_name='클럽'),
        ),
        migrations.AddField(
            model_name='clubtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_tags', to='tags.tag', verbose_name='태그'),
        ),
    ]
