# Generated by Django 3.1.14 on 2022-09-26 22:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import superclub.bases.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('club_board_permission', models.BooleanField(blank=True, null=True, verbose_name='게시판 생성/활성/비활성화 권한')),
                ('club_comment_permission', models.BooleanField(blank=True, null=True, verbose_name='댓글 활성/비활성화 권한')),
                ('club_design_permission', models.BooleanField(blank=True, null=True, verbose_name='클럽 디자인 권한')),
                ('club_modifying_permission', models.BooleanField(blank=True, null=True, verbose_name='정보 수정 권한')),
                ('club_auto_member_registration_permission', models.BooleanField(blank=True, null=True, verbose_name='자동 가입 권한')),
                ('club_approval_member_permission', models.BooleanField(blank=True, null=True, verbose_name='가입 승인 권한')),
                ('club_restriction_activity_permission', models.BooleanField(blank=True, null=True, verbose_name='활동 제한 권한')),
                ('club_restriction_activity_period_permission', models.BooleanField(blank=True, null=True, verbose_name='활동 제한 기간 설정 권한')),
                ('club_banishment_permission', models.BooleanField(blank=True, null=True, verbose_name='퇴출 권한')),
                ('club_restriction_approval_member_period_permission', models.BooleanField(blank=True, null=True, verbose_name='가입 제한 기간 설정 꿘한')),
                ('club_block_permission', models.BooleanField(blank=True, null=True, verbose_name='차단 권한')),
                ('club_hand_over_permission', models.BooleanField(blank=True, null=True, verbose_name='양도 권한')),
                ('club_transfer_permission', models.BooleanField(blank=True, null=True, verbose_name='이전 권한')),
                ('club_independence_permission', models.BooleanField(blank=True, null=True, verbose_name='독립 권한')),
                ('club_merge_permission', models.BooleanField(blank=True, null=True, verbose_name='합병 권한')),
                ('club_closure_permission', models.BooleanField(blank=True, null=True, verbose_name='폐쇄 권한')),
                ('club_post_permission', models.BooleanField(blank=True, null=True, verbose_name='게시글 활성/비활성화 권한')),
                ('club_staff_permission', models.BooleanField(blank=True, null=True, verbose_name='스태프 임명/취소 권한')),
                ('club_modify_permission_by_staff_permission', models.BooleanField(blank=True, null=True, verbose_name='스탭별 권한 수정 권한')),
                ('club_static_permission', models.BooleanField(blank=True, null=True, verbose_name='통계 관리 권한')),
                ('comment_count', models.IntegerField(default=0, verbose_name='댓글 수')),
                ('post_count', models.IntegerField(default=0, verbose_name='게시글 수')),
                ('visit_count', models.IntegerField(default=0, verbose_name='방문 수')),
                ('club_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='클럽 이름')),
                ('user_email', models.CharField(blank=True, max_length=60, null=True, verbose_name='유저 이메일')),
                ('user_data', models.JSONField(blank=True, null=True, verbose_name='유저')),
                ('point', models.IntegerField(default=0, verbose_name='점수')),
                ('level', models.IntegerField(default=1, verbose_name='레벨')),
                ('grade', models.IntegerField(choices=[(1, 'BRONZE'), (2, 'SILVER'), (3, 'GOLD'), (4, 'PLATINUM'), (5, 'DIAMOND'), (6, 'LEGEND')], default=1, verbose_name='등급')),
                ('staff', models.IntegerField(blank=True, choices=[(7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], null=True, verbose_name='스태프')),
                ('is_staff', models.BooleanField(default=False, verbose_name='스태프 여부')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='clubs.club', verbose_name='클럽')),
            ],
            options={
                'verbose_name': '클럽 프로필',
                'verbose_name_plural': '클럽 프로필',
                'db_table': 'profiles',
                'ordering': ['-created'],
            },
            bases=(superclub.bases.models.UpdateMixin, models.Model),
        ),
    ]
