# Generated by Django 3.1.14 on 2022-09-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220926_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='grade_name',
            field=models.CharField(default='BRONZE', max_length=100, verbose_name='등급 이름'),
        ),
        migrations.AddField(
            model_name='profile',
            name='staff_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='스태프 이름'),
        ),
    ]
