# Generated by Django 3.1.14 on 2022-09-26 22:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import superclub.apps.posts.models.index
import superclub.apps.posts.models.mixins_post.image
import superclub.bases.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0002_auto_20220926_2255'),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('comment_count', models.IntegerField(default=0, verbose_name='댓글 수')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to=superclub.apps.posts.models.mixins_post.image.image_path, verbose_name='썸네일 이미지')),
                ('thumbnail_image_url', models.URLField(blank=True, null=True, verbose_name='썸네일 이미지 URL')),
                ('like_count', models.IntegerField(default=0, verbose_name='좋아요 수')),
                ('dislike_count', models.IntegerField(default=0, verbose_name='싫어요 수')),
                ('share_count', models.IntegerField(default=0, verbose_name='공유 수')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('club_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='클럽 이름')),
                ('board_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='게시판 이름')),
                ('user_email', models.CharField(blank=True, max_length=60, null=True, verbose_name='유저 이메일')),
                ('profile_data', models.JSONField(blank=True, null=True, verbose_name='프로필 데이터')),
                ('title', models.CharField(default='Untitled', max_length=100, verbose_name='제목')),
                ('content', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('popularity', models.IntegerField(default=0, verbose_name='인기')),
                ('is_video', models.BooleanField(default=False, verbose_name='비디오 게시글 여부')),
                ('is_image', models.BooleanField(default=False, verbose_name='이미지 게시글 여부')),
                ('is_temporary', models.BooleanField(default=False, verbose_name='임시글 여부')),
                ('is_secret', models.BooleanField(default=False, verbose_name='비밀글 여부')),
                ('password', models.IntegerField(blank=True, null=True, verbose_name='비밀번호')),
                ('is_notice', models.BooleanField(default=False, verbose_name='공지 여부')),
                ('is_event', models.BooleanField(default=False, verbose_name='이벤트 여부')),
                ('is_comment', models.BooleanField(default=True, verbose_name='댓글 여부')),
                ('is_share', models.BooleanField(default=True, verbose_name='공유 여부')),
                ('is_search', models.BooleanField(default=True, verbose_name='검색 여부')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='boards.board', verbose_name='게시판')),
                ('board_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='boards.boardgroup', verbose_name='게시판 그룹')),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='clubs.club', verbose_name='클럽')),
            ],
            options={
                'verbose_name': '포스트',
                'verbose_name_plural': '포스트',
                'db_table': 'posts',
                'ordering': ['-created'],
            },
            bases=(superclub.bases.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PostVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('video', models.FileField(upload_to='', verbose_name='비디오')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='비디오 URL')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='썸네일 이미지')),
                ('thumbnail_image_url', models.URLField(blank=True, null=True, verbose_name='썸네일 이미지 URL')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_videos', to='posts.post', verbose_name='포스트')),
            ],
            options={
                'verbose_name': '포스트 비디오',
                'verbose_name_plural': '포스트 비디오',
                'db_table': 'post_videos',
                'ordering': ['-created'],
            },
            bases=(superclub.bases.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('image', models.ImageField(upload_to=superclub.apps.posts.models.index.PostImage.image_path, verbose_name='이미지')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='이미지 URL')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='썸네일 이미지')),
                ('thumbnail_image_url', models.URLField(blank=True, null=True, verbose_name='썸네일 이미지 URL')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='posts.post', verbose_name='포스트')),
            ],
            options={
                'verbose_name': '포스트 이미지',
                'verbose_name_plural': '포스트 이미지',
                'db_table': 'post_images',
                'ordering': ['-created'],
            },
            bases=(superclub.bases.models.UpdateMixin, models.Model),
        ),
    ]
