# Generated by Django 3.1.14 on 2022-09-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='report_count',
            field=models.IntegerField(default=0, verbose_name='신고 수'),
        ),
    ]
