# Generated by Django 3.1.14 on 2022-09-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='board_group_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='게시판 그룹 이름'),
        ),
    ]
