# Generated by Django 3.1.14 on 2022-09-29 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20220927_2031'),
        ('posts', '0006_post_board_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='boards.board', verbose_name='게시판'),
        ),
        migrations.AlterField(
            model_name='post',
            name='board_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='boards.boardgroup', verbose_name='게시판 그룹'),
        ),
    ]
