# Generated by Django 3.1.14 on 2022-09-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220929_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pin_count',
            field=models.IntegerField(default=0, verbose_name='핀 수'),
        ),
    ]
