# Generated by Django 3.1.14 on 2022-09-27 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import superclub.bases.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0004_post_report_count'),
        ('profiles', '0002_auto_20220926_2255'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0005_comment_report_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('type', models.CharField(choices=[('SPAM', '스팸 홍보/도배글 입니다.'), ('PORNOGRAPHY', '음란물 입니다.'), ('ILLEGAL', '불법정보를 포함하고 있습니다.'), ('HARMFUL', '청소년에게 유해한 내용입니다.'), ('ABUSE', '욕설, 비방, 차별, 혐오 표현입니다.'), ('PRIVACY', '개인정보 노출 게시물입니다.'), ('ETX', '기타')], max_length=100, verbose_name='타입')),
                ('content', models.CharField(blank=True, max_length=500, null=True, verbose_name='내용')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_reports', to='posts.post', verbose_name='게시글')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_reports', to='profiles.profile', verbose_name='프로필')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_reports', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '게시글 신고',
                'verbose_name_plural': '게시글 신고',
                'db_table': 'post_reports',
                'ordering': ['-created'],
            },
            bases=(superclub.bases.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('type', models.CharField(choices=[('SPAM', '스팸 홍보/도배글 입니다.'), ('PORNOGRAPHY', '음란물 입니다.'), ('ILLEGAL', '불법정보를 포함하고 있습니다.'), ('HARMFUL', '청소년에게 유해한 내용입니다.'), ('ABUSE', '욕설, 비방, 차별, 혐오 표현입니다.'), ('PRIVACY', '개인정보 노출 게시물입니다.'), ('ETX', '기타')], max_length=100, verbose_name='타입')),
                ('content', models.CharField(blank=True, max_length=500, null=True, verbose_name='내용')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_reports', to='comments.comment', verbose_name='댓글')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_reports', to='profiles.profile', verbose_name='프로필')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_reports', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '댓글 신고',
                'verbose_name_plural': '댓글 신고',
                'db_table': 'comment_reports',
                'ordering': ['-created'],
            },
            bases=(superclub.bases.models.UpdateMixin, models.Model),
        ),
    ]
