# Generated by Django 3.1.14 on 2022-09-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreport',
            name='profile_data',
            field=models.JSONField(blank=True, null=True, verbose_name='프로필 데이터'),
        ),
        migrations.AddField(
            model_name='postreport',
            name='profile_data',
            field=models.JSONField(blank=True, null=True, verbose_name='프로필 데이터'),
        ),
    ]
